### ISSUE TITLE
Some links are currently unreachable and need to be updated.

### ISSUE THREAD

**Issue by skywalker512** [waterholeforum/core#1]
### Bug description

Some links in GitHub cannot be opened and need to be updated.

### Steps to reproduce

- Waterhole skeleton repository
https://github.com/waterholeforum/core/blob/main/README.md?plain=1#L9

- https://github.com/waterholeforum/core/issues/new/choose
  Feature Requests and Ideas
  https://waterhole.dev/community/channel/ideas -> https://waterhole.dev/community/channels/ideas

- https://waterhole.dev/community/channels/extensions
   https://waterhole.dev/community/channel/development -> https://waterhole.dev/community/channels/development

### Environment

```yaml
no need Environment
```

**Comment by tobyzerner** [comment]
Thank you for reporting these!
