### ISSUE TITLE
Invalid Key Clicks on Safari for Mac Desktop

### ISSUE THREAD

**Issue by efast1568** [waterholeforum/core#11]
### Bug description

The layout of Safari on a Mac is notoriously poor, which is not surprising. 
However, the majority of  all dropdown menus are not functional when clicked, and this issue needs to be addressed as a priority.

![螢幕快照 2023-06-04 下午10 13 40](https://github.com/waterholeforum/core/assets/105265831/1ac4c503-c28d-462a-9c34-dbf50a2a8f50)

### Steps to reproduce

N/A

### Logs

```shell
N/A
```

### Environment

```yaml
N/A
```

**Comment by tobyzerner** [comment]
This looks like a fairly old version of Safari. Waterhole supports 14.1+
