### ISSUE TITLE
Color picker doesn't allow manual editing

### ISSUE THREAD

**Issue by renegalindo** [waterholeforum/core#15]
### Bug description

When trying to manually edit a color in the picker, any click or "slide" attempt will close it.

### Steps to reproduce

1. Try editing the badge color of a User Group.
2. Then click the color picker.

### Environment

```yaml
Waterhole 0.2
```

**Comment by tobyzerner** [comment]
Browser?

**Comment by renegalindo** [comment]
Chrome on MacOS 13.4
