### ISSUE TITLE
Front-end symbol for the header title in the article's header

### ISSUE THREAD

**Issue by efast1568** [waterholeforum/core#16]
### Bug description

```
.header-breadcrumb:before {
content: " › ";
margin: 0 var(--space-xs);
}
```
[Imgur](https://imgur.com/KYMAMdu)

There is a chance that the content may appear as garbled characters due to encoding issues.

Suggested correction:
`content: "\203A";`

### Steps to reproduce

N/A

### Logs

```shell
N/A
```

### Environment

```yaml
N/A
```

**Comment by tobyzerner** [comment]
Fixed in 9383422
