### ISSUE TITLE
Display behavior of tooltips on the controller

### ISSUE THREAD

**Issue by efast1568** [waterholeforum/core#17]
### Bug description

Is it possible to adjust the display of tooltips on the main controller to the left side? Currently, they are covering the main buttons.
When the mouse passes over from below, there is a possibility that it might block the button I intend to press.

https://imgur.com/XeTqfkW
At the same time, I believe this tip is not essential. Perhaps consider removing it.

### Steps to reproduce

N/A

### Logs

```shell
N/A
```

### Environment

```yaml
N/A
```

**Comment by tobyzerner** [comment]
The tooltip is important to explain the actual effect of following a post to new users. I've moved it to the bottom and added a longer delay.
