### ISSUE TITLE
The admin area not complete

### ISSUE THREAD

**Issue by Temian1** [waterholeforum/core#29]
### Bug description

Checking the demo and I realize admin can't manage post or comment, thier is no separate moderator dashboard where they can Manage the channel and post and comment they are in charge with

So many missing features

And there is no documentation on how to create extensions 

### Steps to reproduce

K

### Logs

```shell
K
```

### Environment

```yaml
K
```

**Comment by tobyzerner** [comment]
Hi @Temian1, this is not a very helpful issue report - you'll need to be much more specific. Admins can manage posts and comments. There is comprehensive [documentation](https://waterhole.dev/docs/main/extending) on extending Waterhole. If you have a specific feature request, please feel free to share it in the Waterhole community [Ideas channel](https://waterhole.dev/community/channels/ideas).
