### ISSUE TITLE
419 Page Expired Issue

### ISSUE THREAD

**Issue by efast1568** [waterholeforum/core#33]
### Bug description

On mobile/desktop devices, I often encounter a 419 Page Expired error when trying to log in. Unfortunately, I cannot provide exact replication steps. It seems to occur more frequently when multiple waterholes are open.

This issue happens both on the waterhole.dev & demo  and on my test site. In fact, it has been a common occurrence since I started using waterhole. Typically, I have to close the browser and restart the page to log in successfully.

I am just sharing this information with you, and I'm not certain if it is a bug or not.

https://i.imgur.com/A3vfx6a.mp4 

### Steps to reproduce

N/A

### Logs

```shell
N/A
```

### Environment

```yaml
N/A
```

**Comment by tobyzerner** [comment]
This error occurs due to the CSRF token that is submitted with the form being invalid. By default, sessions (and their CSRF tokens) expire after 2 hours of inactivity (this is the Laravel default, can be configured in `config/session.php`). So is it possible that you are leaving the login page open for >2 hours and then submitting the form?

**Comment by efast1568** [comment]
I don't think  it's due to the 2-hour limit because most of the time, this occurs during continuous usage. Is there any limitation when it comes to multiple window logins? I will get more try to see if I can accurately reproduce this issue.

**Comment by efast1568** [comment]
It should not be caused by waterhole, maybe this issue can be closed

https://laracasts.com/discuss/channels/laravel/419-login-link-expired-errors-on-mobile-only?page=1&replyId=867897

```
The core issue is that Google Chrome on mobile now automatically tries to submit the "Log In" form for you when using its password manager. [1]

So, if you are like me, you are inadvertently submitting the form twice..

First, when you select your password (per [1])
Second, when you click the "Log In" button
The second click is what causes the 419 error, and is why a simple refresh, after you see the 419 error, indicates that you are logged in.

This behavior isn't really Laravel's fault, but it is so annoying and pernicious, it should probably be addressed in the core.
```
