### ISSUE TITLE
Images are deformed by max-height

### ISSUE THREAD

**Issue by renegalindo** [waterholeforum/core#35]
### Bug description

Images have a `max-height` of 70vh, which can cause distortion in some cases.

### Steps to reproduce

Check out the image in this post: https://blank.page/cafe/posts/22-blank-page-is-my-journaling-app

### Environment

```yaml
Waterhole 0.3
```

**Comment by renegalindo** [comment]
Any updates on this? Here's another example where it's quite evident: https://blank.page/cafe/posts/35-from-email-to-specs-country-songs-and-beyond

**Comment by efast1568** [comment]
> Any updates on this? Here's another example where it's quite evident: https://blank.page/cafe/posts/35-from-email-to-specs-country-songs-and-beyond

I just use CSS
```
:where(.content) img:not([class]) {
    max-height: none;
}
```
