### ISSUE TITLE
Installs v0.2.0 by default

### ISSUE THREAD

**Issue by AlexanderFalkenberg** [waterholeforum/core#38]
### Bug description

Just run the installation as per the documentation. I noticed it installs the v0.2.0 version instead of v0.3.0. 

### Steps to reproduce

Run composer create-project waterhole/waterhole path/to/forum

### Logs

```shell
composer create-project waterhole/waterhole waterhole_two
Creating a "waterhole/waterhole" project at "./waterhole_two"
Installing waterhole/waterhole (v0.2.0)
  - Installing waterhole/waterhole (v0.2.0): Extracting archive
```

### Environment

```yaml
Terminal
```

**Comment by tobyzerner** [comment]
Thank you for pointing this out! I've tagged a new version of `waterhole/waterhole` so should be fixed now.
