### ISSUE TITLE
Changes in blade-tabler-icons  v2.4.8 filled/outline

### ISSUE THREAD

**Issue by efast1568** [waterholeforum/core#63]
### Bug description

The display  of blade-tabler-icons has changed after v2.48 ?
![螢幕擷取畫面 2024-03-15 111740](https://github.com/waterholeforum/core/assets/105265831/d09fe846-3f0b-40fe-a5f9-f46080e4fcd3)

https://github.com/secondnetwork/blade-tabler-icons/issues/57
Perhaps it should be limited to v2.47 for now.
![image](https://github.com/waterholeforum/core/assets/105265831/b4ef75c5-7260-46f3-ac2b-64efb4632880)

### Steps to reproduce

N/A

### Environment

```yaml
N/A
```

**Comment by tobyzerner** [comment]
Thanks for reporting this!
