### ISSUE TITLE
"Show more" renders incorrectly on Firefox

### ISSUE THREAD

**Issue by nkvname** [waterholeforum/core#64]
### Bug description

Any pages that contains "Show more" is incorrectly rendered in Firefox https://waterhole.dev/community/channels/blog
Results are not the same as on Chrome based browsers:

Desktop version:
![2024-03-j4ilh](https://github.com/waterholeforum/core/assets/23085334/f69bbf86-761a-4893-868d-625f6c8e4880)

Android version: 
![Screenshot_2024_03_21_11_43_35_25_3aea4af51f236e4932235fdada7d1643](https://github.com/waterholeforum/core/assets/23085334/3d806735-9c9d-4424-8b6e-d4e25735bbd0)

### Steps to reproduce

Open any page with "Show more" in Firefox. 

### Environment

```yaml
Firefox 123.0.1 (with and without add-ons) 
Firefox Beta 124.0 (with and without add-ons) 
Firefox Android (124.0)
Waterhole 0.4.7
```

**Comment by efast1568** [comment]
On your  site, you can use the following CSS for now. This is how I currently solved it:

.truncated__expander {
  width: -moz-available;
}
