### ISSUE TITLE
Font issues in the left sidebar on Firefox

### ISSUE THREAD

**Issue by nkvname** [waterholeforum/core#78]
### Bug description

On Firefox, letters "g" and "b" in the waterholes left sidebar are not displayed properly; they appear to be cut off slightly. This issue does not occur on Chrome-based browsers.

Note: No issues on Firefox mobile (Android version). 

![2024-05-DqpKf](https://github.com/waterholeforum/core/assets/23085334/5c24b16b-87d2-4d68-b236-e9354d2ecd20)

### Steps to reproduce

Open any page that runs Waterhole in Firefox. For example "Worklogs" on https://cafe.blank.page

### Environment

```yaml
Waterhole 0.4.8
Firefox stable 125.0.3 (Windows 10)
Firefox beta 126.0 (Windows 10)
Screen size does not matter
```

**Comment by tobyzerner** [comment]
Unfortunately I don't have Windows and unable to reproduce this on Mac. There's also no obvious cause looking at the CSS. If someone with Windows can investigate/debug further that would be appreciated - but otherwise I'm tempted to call this a Firefox bug.
